import { defineType } from 'sanity'

export const siteConfigType = defineType({
  name: 'siteConfig',
  title: 'Configuración del Sitio',
  type: 'document',
  groups: [
    { name: 'contact', title: 'Contacto', default: true },
    { name: 'hero', title: 'Hero' },
    { name: 'footer', title: 'Footer' },
    { name: 'intro', title: 'Intro' },
  ],
  fields: [
    {
      name: 'email',
      title: 'Email de contacto',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'phone',
      title: 'Teléfono',
      type: 'string',
      group: 'contact',
    },
    {
      name: 'businessHours',
      title: 'Horario de atención',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Ej: "Lunes a Viernes: 9:00 - 18:00"',
      group: 'contact',
    },
    {
      name: 'whyChooseUs',
      title: '¿Por qué elegirnos?',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'contact',
    },
    {
      name: 'heroTitle',
      title: 'Hero - Título principal',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroSubtitle',
      title: 'Hero - Subtítulo',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroDescription',
      title: 'Hero - Descripción',
      type: 'text',
      rows: 3,
      group: 'hero',
    },
    {
      name: 'heroPrimaryCtaText',
      title: 'Hero - Texto botón principal',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroPrimaryCtaTarget',
      title: 'Hero - ID destino botón principal',
      type: 'string',
      description: 'Ej: contact o portfolio',
      group: 'hero',
    },
    {
      name: 'heroSecondaryCtaText',
      title: 'Hero - Texto botón secundario',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroSecondaryCtaTarget',
      title: 'Hero - ID destino botón secundario',
      type: 'string',
      description: 'Ej: portfolio o contact',
      group: 'hero',
    },
    {
      name: 'footerBrandTitle',
      title: 'Footer - Título marca',
      type: 'string',
      description: 'Ej: cetresdé',
      group: 'footer',
    },
    {
      name: 'footerDescription',
      title: 'Footer - Descripción',
      type: 'text',
      rows: 3,
      group: 'footer',
    },
    {
      name: 'footerQuickLinks',
      title: 'Footer - Enlaces rápidos',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'label', title: 'Etiqueta', type: 'string' },
            {
              name: 'targetId',
              title: 'ID destino',
              type: 'string',
              description: 'Usa top para ir arriba o el id de sección, por ejemplo contact',
            },
          ],
        },
      ],
      group: 'footer',
    },
    {
      name: 'footerServices',
      title: 'Footer - Lista de servicios',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'footer',
    },
    {
      name: 'footerCopyrightText',
      title: 'Footer - Copyright',
      type: 'string',
      description: 'Ej: © 2026 cetresdé. Todos los derechos reservados.',
      group: 'footer',
    },
    {
      name: 'introOverlay',
      title: 'Intro Overlay (Landing VFX)',
      type: 'object',
      group: 'intro',
      fields: [
        {
          name: 'enabled',
          title: 'Activar intro',
          type: 'boolean',
          initialValue: true,
          description: 'Muestra el overlay al cargar la página (solo una vez por sesión)',
        },
        {
          name: 'displayPolicy',
          title: 'Frecuencia de visualización',
          type: 'string',
          initialValue: 'once-per-session',
          options: {
            list: [
              { title: 'En cada recarga', value: 'every-load' },
              { title: 'Una vez por sesión', value: 'once-per-session' },
            ],
            layout: 'radio',
          },
          description: 'Controla si la intro aparece siempre o solo una vez por sesión.',
        },
        {
          name: 'imageSrc',
          title: 'Imagen (ruta en /public)',
          type: 'string',
          description: 'Ej: /intro/intro-landing.webp',
        },
        {
          name: 'title',
          title: 'Título',
          type: 'string',
          description: 'Ej: Capricho Azahar 3D',
        },
        {
          name: 'subtitle',
          title: 'Subtítulo',
          type: 'string',
          description: 'Ej: Donde las ideas toman forma',
        },
        {
          name: 'durationMs',
          title: 'Duración (ms)',
          type: 'number',
          initialValue: 4500,
          description: 'Tiempo que se muestra la intro antes de cerrar automáticamente',
        },
        {
          name: 'imageDisplayMode',
          title: 'Modo de encuadre de imagen',
          type: 'string',
          initialValue: 'cinematic',
          options: {
            list: [
              { title: 'Cinematic (fondo + imagen completa)', value: 'cinematic' },
              { title: 'Contain (imagen completa)', value: 'contain' },
              { title: 'Cover (pantalla completa recortada)', value: 'cover' },
            ],
            layout: 'radio',
          },
          description: 'Controla cómo se muestra la imagen de la intro en pantalla.',
        },
      ],
    },
  ],
})
